version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.16
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    restart: always
    tty: true
    # volumes:
    #     - ./data:/var/lib/mysql